# Uncomment the following line to enable OLED Displays
CONFIG_ZMK_DISPLAY=y

# Explicitly force Bluetooth (BLE) to compile and run
CONFIG_ZMK_BLE=y

# Force a clear and recognizable Bluetooth name
CONFIG_ZMK_KEYBOARD_NAME="Crosses BT"

# Enable battery reporting and split communication for battery levels
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_FETCHING=y
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_PROXY=y
